name: Build the flutter version of the RustDesk

on:
  workflow_dispatch:
    inputs:
      upload-artifact:
        type: boolean
        description: 'Upload Artifacts'
        default: true
  push:
    branches: [ "master" ]
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      upload-tag:
        type: string
        default: "nightly"

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # <--- VITAL: Mantenemos esto

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      # --- CORRECCIÓN 1: Instalar LLVM (Necesario para bindgen) ---
      - name: Instalar LLVM y Clang
        run: choco install llvm -y
        shell: cmd

      # --- CORRECCIÓN 2: Instalar Dependencias (Modo Manifiesto) ---
      # Ejecutamos vcpkg sin argumentos para que lea vcpkg.json
      - name: Instalar Dependencias Vcpkg
        run: vcpkg install
        shell: cmd

      - name: Build RustDesk (Release)
        env:
          RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
          RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
          # --- CORRECCIÓN 3: Variables de Entorno para Clang ---
          # Le decimos a Rust dónde encontrar la librería que acabamos de instalar
          LIBCLANG_PATH: 'C:\Program Files\LLVM\bin'
          LLVM_INSTALL_PATH: 'C:\Program Files\LLVM'
        run: python3 build.py --flutter --hwcodec
        shell: cmd

      # --- EMPAQUETADO ---
      - name: Instalar Inno Setup (Nativo)
        run: choco install innosetup --no-progress
        shell: cmd

      - name: Compilar Instalador .exe
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup.iss
        shell: cmd

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Abasur-Instalador-Windows
          path: Output/Abasur_Instalador_Full.exe
